#Numero menor
print(" ")
print ("Ordonez Martinez Valeria, 3W, Examen primer parcial, ej.5.1")
print (" ")
#Titulo de primer ejercicio
print("Numero menor")
#Declarar valor 1
a=input("Ingrese el primer valor: ")
#Declarar valor 2
b=input("Ingrese el segundo valor: ")

#Agregar una condicion si a es menor b
if a<b:
    #Imprimir si a es menor
    print (a, " es menor")
    #Agregar condicion si b es menor que a
elif b<a:
    #Imprimir que b es menor
    print (b, " es menor")
    #Si ninguna de los variables es menor que la otra se pone else
else:
    print ("Ninguno de los dos numero es menor al otro")
print(" ")


    


